<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ch.html</string>
		<string>pl.php</string>
		<string>sn.php</string>
		<string>tp.html</string>
	</array>
	<key>name</key>
	<string>MODX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[\[-</string>
			<key>end</key>
			<string>\]\]</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\[</string>
			<key>end</key>
			<string>[\]]{2,}</string>
			<key>name</key>
			<string>constant.character.modx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(!|\+|\+\+|\$|\*|~|%)</string>
					<key>name</key>
					<string>keyword.control.modx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&amp;)([A-Za-z0-9_]+)(=)</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(:)([A-Za-z0-9_]+)</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Za-z0-9_\.]*)</string>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>string.control.single.modx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>constant.character.escape.modx</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.modx</string>
	<key>uuid</key>
	<string>e26dbef2-f545-436d-b34f-37386d89b03c</string>
</dict>
</plist>
